django_site/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('steamdb/', include('steamdb.urls')),
]

steamdb/urls.py
from django.urls import path

from . import views

app_name = "steamdb"

urlpatterns = [
    path('summary/', views.app_summary, name="app_summary"),
    path('detail/<int:app_id>/', views.app_detail, name="app_detail"),
    path('edit/<int:app_id>/', views.app_edit, name="app_edit"),
    path('add/', views.app_add, name="app_add"),
    path('delete/<int:app_id>/', views.app_delete, name="app_delete"),
    path('catch/', views.app_catch, name="app_catch"),
]

steamdb/models.py
#! /usr/bin/python3.7

import datetime

from django.db import models
from django.utils.timezone import now


class SteamDB(models.Model):

    app_id = models.IntegerField("Steam ID")
    app_name = models.CharField("app name", max_length=300, default="NULL")
    app_desc = models.TextField("app glance", max_length=500, default="NULL")
    app_publisher = models.CharField("app publisher", max_length=200, default="NULL")
    app_developer = models.CharField("app developer", max_length=200, default="NULL")
    app_history_reviews = models.TextField("app history reviews", max_length=500, default="NULL")
    app_recent_reviews = models.TextField("app recent reviews", max_length=500, default="NULL")
    app_thumbnail = models.ImageField("app thumbnail", upload_to="steamdb/static/documents/", default="")
    app_tag = models.CharField("app Tags", max_length=500, default="NULL")
    app_release_date = models.DateTimeField("Release Date", default=now)
    app_price = models.FloatField("app price", default=0.0)
    app_news = models.TextField("app news", max_length=1000, default="NULL")
    app_info_complete = models.BooleanField("app info complete", default=False)

    def __str__(self):
        return self.app_name

    def _is_release_recently(self):
        return self.app_release_date >= now() - datetime.timedelta(days=100)

steamdb/forms.py
from django import forms

from .models import SteamDB


class AppEditForm(forms.ModelForm):
    class Meta:
        model = SteamDB
        fields = (
            'app_desc',
            'app_tag',
            'app_publisher',
            'app_developer',
            'app_history_reviews',
            'app_recent_reviews',
            'app_release_date',
            'app_price',
            'app_news',
            'app_thumbnail',
        )

steamdb/views.py
#! /usr/bin/python3.7

from collections import deque
from datetime import datetime
from io import BytesIO
from PIL import Image
import requests


from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.template import loader
from django.urls import reverse

from .forms import AppEditForm
from .models import SteamDB
from .utils.app_operator import AppOperator


def app_summary(request):
    app_deque = deque(maxlen=50)
    template = loader.get_template("steamdb/summary.html")
    app_list = SteamDB.objects.order_by("-app_id")
    app_deque.extend(app_list)
    context = {
        'app_list': app_deque
    }

    return HttpResponse(template.render(context, request))


def app_detail(request, app_id):
    template = loader.get_template("steamdb/detail.html")
    app_obj = get_object_or_404(SteamDB, app_id=app_id)

    app_opt = AppOperator()
    data = app_opt.get_app_info(app_id).get(str(app_id)).get("data")
    if not app_obj.app_info_complete:
        app_obj.app_desc = data.get("short_description")
        # update header image
        thumbnail_url = data.get("header_image").replace(" ", "")
        r = requests.get(thumbnail_url)
        name = "steamdb/static/documents/header_%s.jpg" % app_id
        image = Image.open(BytesIO(r.content))
        image.save(name)
        app_obj.app_thumbnail = name.replace("steamdb/static/", "")
        app_obj.app_publisher = data.get("publishers")
        app_obj.app_developer = data.get("developers")
        app_obj.app_tag = "/".join([item["description"] for item in data.get("categories")])
        app_obj.app_price = data.get("price_overview", {}).get("final", 0) / 100
        date = data.get("release_date", {}).get("date")
        if date:
            dt = datetime.strptime(date, "%d %b, %Y")
            app_obj.app_release_date = dt.strftime("%Y-%m-%d")

        app_obj.app_info_complete = True
        app_obj.save()

    form = AppEditForm()
    context = {
        "app": app_obj,
        "app_edit_form": form
    }
    return HttpResponse(template.render(context, request))


def app_edit(request, app_id):
    app_obj = get_object_or_404(SteamDB, app_id=app_id)
    for key, value in request.POST.items():
        if not hasattr(app_obj, key):
            continue
        setattr(app_obj, key, value)
    app_obj.save()
    app_thumbnail = request.FILES.get("app_thumbnail")
    if app_thumbnail:
        fs = FileSystemStorage()
        name = "steamdb/static/documents/header_%s.%s" %\
               (app_id, app_thumbnail.name.split(".")[-1])
        filename = fs.save(name, app_thumbnail)
        app_obj.app_thumbnail = fs.url(filename).replace("steamdb/static/", "")
        app_obj.save()

    return HttpResponseRedirect(reverse('steamdb:app_detail', args=(app_id,)))


def app_add(request):
    app_obj = SteamDB()
    for key, value in request.POST.items():
        if not hasattr(app_obj, key):
            continue
        setattr(app_obj, key, value)
    app_obj.save()

    return HttpResponseRedirect(reverse('steamdb:app_summary', args=()))


def app_delete(request, app_id):
    app_obj = get_object_or_404(SteamDB, app_id=app_id)
    app_obj.delete()
    return HttpResponseRedirect(reverse('steamdb:app_summary', args=()))


def app_catch(request):
    app_opt = AppOperator()
    app_list = app_opt.get_app_list()
    for app in app_list:
        try:
            app_model = SteamDB(app_id=app["appid"], app_name=app["name"])
            app_model.save()
        except Exception:
            continue
    return HttpResponseRedirect(reverse('steamdb:app_summary', args=()))

steamdb/templates/steamdb/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://libs.baidu.com/jquery/1.10.2/jquery.min.js"></script>
    <script>
        {% block script %}
        {% endblock %}
    </script>
    <style>
        html * {
            font-family: "Microsoft YaHei", serif
        }
        #edit_field {
            border-color: mediumorchid;
            border-width: 5px;
            border-style: solid;
            width: 1600px;
        }
        #add_app_field {
            border-color: mediumorchid;
            border-width: 5px;
            border-style: solid;
        }
        form.edit_form input {
            position: absolute;
            left: 200px;
            width: 600px;
        }
        form.edit_form textarea {
            position: sticky;
            left: 200px;
            width: 1200px;
            height: 50px;
        }

        .add_input {
            position: absolute;
            left: 200px;
            width: 1200px;
        }
    </style>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

steamdb/templates/steamdb/detail.html
{% extends 'steamdb/base.html' %}
{%  load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>app Detail</title>
    <script>
        {% block script %}
            $(document).ready(function(){
                $("#edit_field").hide()
                $("#edit_button").click(function () {
                    $("#edit_field").show()
                    $("#edit_button").hide()
                });
                $("#cancel_button").click(function () {
                    $("#edit_field").hide()
                    $("#edit_button").show()
                })

            });
        {% endblock %}
    </script>
</head>
<body>
{% block body %}
    <h1>NAME:{{ app.app_name }}</h1>
    <p>ID:{{ app.app_id }}</p>
    <p style="width: 1200px;">AT A GLANCE:{{ app.app_desc }}</p>
    <p style="width: 1200px;">TAGS:{{ app.app_tag }}</p>
    <p>PUBLISHER:{{ app.app_publisher }}</p>
    <p>DEVELOPER:{{ app.app_developer }}</p>
    <p>HISTORY REVIEWS:{{ app.app_history_reviews }}</p>
    <p>RECENT REVIEWS:{{ app.app_recent_reviews }}</p>
    {% if app.app_thumbnail %}
        <p><img src="{% static app.app_thumbnail.url %}" alt="header image"></p>
    {% else %}
        <p><img src="" alt="header image"></p>
    {% endif %}
    <p>RELEASE DATE:{{ app.app_release_date }}</p>
    <p>PRICE:{{ app.app_price }}</p>
    <p>NEWS:{{ app.app_news }}</p>
    <p><a href="https://store.steampowered.com/app/{{ app.app_id }}" target="_blank">steam link</a></p>

    <button id="edit_button" value="EDIT">EDIT</button>
    <form action="{% url 'steamdb:app_delete' app.app_id %}" method="post" style="display: inline">
    {%  csrf_token %}
        <input type="submit" value="DELETE">
    </form>
    <br><br>

    <fieldset id="edit_field">
    <legend>Edit app info</legend>
        <form method="post" enctype="multipart/form-data"
              class="edit_form" action="{% url 'steamdb:app_edit' app.app_id %}"
              style="display: inline">
        {% csrf_token %}
            {{ app_edit_form.as_p }}
        <button type="submit">SUBMIT</button>
        </form>
        <button id="cancel_button">CANCEL</button>
    </fieldset>

    <a href="{% url 'steamdb:app_summary' %}">BACK TO SUMMARY</a>
{% endblock %}
</body>
</html>

steamdb/templates/steamdb/summary.html
{%  extends 'steamdb/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SteamDB Summary</title>
    <script>
        {% block script %}
            $(function () {
                $("#add_app_field").hide();
                $("#cancel_button").hide();
                $("#add_app_button").click(function () {
                    $("#add_app_button").hide();
                    $("#add_app_field").show();
                    $("#cancel_button").show();
                });
                $("#cancel_button").click(function () {
                    $("#add_app_button").show();
                    $("#add_app_field").hide();
                    $("#cancel_button").hide();
                });
            });
        {% endblock %}
    </script>
</head>
<body>
{% block body %}

    <fieldset id="add_app_field">
    <legend>Add app info</legend>
        <form action="{% url 'steamdb:app_add' %}" method="post">
        {% csrf_token %}
            app name:
            <input type="text" value="null" name="app_name" class="add_input"><br>
            app id:
            <input type="text" value="null" name="app_id" class="add_input"><br>
            at a glance:
            <input type="text" value="null" name="app_desc" class="add_input"><br>
            app tag:
            <input type="text" value="null" name="app_tag" class="add_input"><br>
            <input type="submit" value="ADD">
        </form>
    </fieldset>

    <div style="text-align: center">
        <button id="add_app_button">ADD APP INFO</button>
        <button id="cancel_button">CANCEL</button>
    </div>

    {% if app_list %}
        <ul>
        {% for app in app_list %}
            <li><a href="{% url 'steamdb:app_detail' app.app_id %}">{{ app.app_id }}-{{ app.app_name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No apps are found in database, want catch some?</p>
        <form action="{% url 'steamdb:app_catch' %}" method="get">
        {% csrf_token %}
        <input value="catch", type="submit">
        </form>
    {% endif %}
{% endblock %}
</body>
</html>